 
 /*------------------------------------------------------------------------
    File        : RoleDataAccess
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : aIzota
    Created     : Thu Nov 26 01:04:14 EET 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class DataAccess.RoleDataAccess: 
    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/
        
    constructor public RoleDataAccess (  ):
        super ().
        
    end constructor.

    destructor public RoleDataAccess ( ):

    end destructor.

end class.